name: golangci-lint
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*"
    branches:
      - main
    paths:
      - '*.go'
      - '**/*.go'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - '*.go'
      - '**/*.go'
      - '.github/workflows/lint.yml'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 4m
